const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const html = fs.readFileSync(path.join(__dirname, '../index.html'), 'utf8');
const context = vm.createContext({ data: { players: [], matches: [] } });
vm.runInContext(html.slice(html.indexOf('  // Achievement model:'), html.indexOf('  // Achievement views.')) + '\n' + html.slice(html.indexOf('  function derive(match)'), html.indexOf('  function validData')), context);
const visit = (total, extra = {}) => ({ total, darts: 3, bust: false, double: false, ...extra });
let counter = 0;
const match = (count, totals, extra = {}) => ({ id: 'match-' + counter++, startedAt: '2026-09-10T12:00:00Z', players: Array.from({ length: count }, (_, i) => ({ id: String(i), name: 'Player ' + i })), visits: totals.map(v => typeof v === 'number' ? visit(v) : v), out: 'straight', bestOf: 1, finishMode: count > 2 ? 'placements' : 'first', abandoned: false, ...extra });
const progress = (games, id = '0') => context.buildAchievements(games).get(id);
const keys = state => Object.keys(state.earned).sort();

assert.equal(context.buildAchievements([]).size, 0);
assert.deepEqual(keys(progress([match(2, [])])), []);
const solo = match(1, [180, 121]);
assert.deepEqual(keys(progress([solo])), ['gold', 'ice', 'maximum']);
assert.equal(progress([solo]).progress.regular, 1);
assert.equal(progress([solo]).progress.comeback, 0, 'Solo cannot be a comeback');
assert.deepEqual(keys(progress([match(1, [visit(180, { bust: true })])])), [], 'Bust cannot earn Maximum');
const pending = match(1, [], { pending: ['BULL', 'BULL'] });
assert.equal(progress([pending]).progress.bull, 0, 'Incomplete visits do not unlock');
const bulls = Array.from({ length: 24 }, () => match(1, [visit(50, { darts: 1, hits: ['BULL'] })]));
assert.equal(progress(bulls).earned.bull, undefined);
bulls.push(match(1, [visit(25, { darts: 1, hits: ['25'] })]));
assert.equal(progress(bulls).progress.bull, 24, 'Outer bulls do not count');
bulls.push(match(1, [visit(50, { darts: 1 })]));
assert.equal(progress(bulls).progress.bull, 24, 'Legacy totals cannot imply a bullseye');
const bullBust = match(1, [180, 100, visit(50, { darts: 1, hits: ['BULL'], bust: true })]);
bulls.push(bullBust);
assert.equal(progress(bulls).progress.bull, 25, 'Actual bullseyes count even when the visit busts');
assert.equal(progress(bulls).earned.bull.matchId, bullBust.id);

assert.equal(progress([match(2, [0, 99, 180, 0, 121])]).earned.comeback, undefined, '99 point gap is insufficient');
assert.ok(progress([match(2, [0, 100, 180, 0, 121])]).earned.comeback, '100 point comeback qualifies');
assert.ok(progress([match(2, [0, 180, 180, 0, 121])]).earned.comeback);
assert.equal(progress([match(2, [180, 0, 121])]).earned.comeback, undefined, 'Leading win is not a comeback');
assert.equal(progress([match(3, [0, 180, 180, 180, 121, 0, 121])]).earned.comeback, undefined, 'Later checkout cannot win the leg');
assert.equal(progress([match(2, [0, 180, 0, 121, 0, 180, 0, 121], { bestOf: 3 })]).earned.comeback, undefined, 'Deficits reset between legs');
const abandoned = match(2, [180, 0, 121], { abandoned: true });
assert.equal(progress([abandoned]).earned.gold, undefined);
assert.equal(progress([abandoned]).progress.regular, 0);
assert.ok(progress([abandoned]).earned.maximum, 'Recorded skill visits remain valid');

const games = Array.from({ length: 49 }, () => match(1, [180, 121]));
assert.equal(progress(games).earned.regular, undefined);
games.push(match(1, [180, 121]));
assert.ok(progress(games).earned.regular);
games.pop();
assert.equal(progress(games).earned.regular, undefined, 'Deletion revokes milestone');
const ranked = match(3, [180, 180, 0, 121, 121]);
assert.equal(progress([ranked], '2').progress.regular, 1, 'Last place earns attendance');
assert.equal(progress([ranked], '1').earned.gold, undefined, 'Only the match winner gets First Blood');
ranked.visits.pop();
assert.equal(progress([ranked]).earned.gold, undefined, 'Placements must finish before match milestones');

const late = match(1, [180, visit(121, { recordedAt: '2026-09-12T12:00:00Z' })]);
const early = match(1, [180, visit(121, { recordedAt: '2026-09-11T12:00:00Z' })], { startedAt: '2026-09-11T10:00:00Z' });
assert.equal(progress([late, early]).earned.gold.matchId, early.id, 'Evidence follows the earliest completion');
assert.equal(progress([late, early]).earned.gold.matchDate, false);
assert.equal(progress([solo]).earned.gold.matchDate, true, 'Legacy evidence labels the match date');
assert.equal(progress([late]).earned.gold.matchId, late.id, 'Deleting earliest source uses the next qualifying record');
late.visits.pop();
assert.deepEqual(keys(progress([late])), ['maximum'], 'Undo removes checkout and win rewards');

assert.equal(context.validRewards(undefined), true, 'Older profiles load');
assert.equal(context.validRewards({ name: 'gold', pose: 'mic-drop', pins: ['gold', 'ice'] }), true);
for (const invalid of [null, [], { name: '<script>' }, { pose: 'unknown' }, { pins: ['gold', 'gold'] }, { pins: ['gold', 'ice', 'bull', 'regular'] }]) assert.equal(context.validRewards(invalid), false);
context.data = { players: [{ id: '0', rewards: { name: 'gold', pose: 'bow', pins: ['gold', 'ice'] } }], matches: [solo] };
assert.equal(context.equippedReward({ id: '0' }, 'name').id, 'gold');
assert.equal(context.selectedVictoryPose({ id: '0' }, 'win', 121), 'bow');
context.data.matches = [];
vm.runInContext('achievementCache=null', context);
assert.equal(context.equippedReward({ id: '0' }, 'name'), null, 'Locked equipment is inactive');
assert.equal(context.selectedVictoryPose({ id: '0' }, 'win', 121), 'dance', 'Revoked pose falls back');
assert.equal(context.pinnedRewards({ id: '0' }).length, 0, 'Revoked medals disappear');
console.log('Achievement rules, historical evidence, ties/placements, undo/deletion, and equipment validation passed.');
